//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void enter_DefaultMode_from_RESET(void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void HFXO_enter_DefaultMode_from_RESET(void);
extern void LFXO_enter_DefaultMode_from_RESET(void);
extern void CMU_enter_DefaultMode_from_RESET(void);
extern void ADC0_enter_DefaultMode_from_RESET(void);
extern void ACMP0_enter_DefaultMode_from_RESET(void);
extern void IDAC0_enter_DefaultMode_from_RESET(void);
extern void RTC_enter_DefaultMode_from_RESET(void);
extern void USART0_enter_DefaultMode_from_RESET(void);
extern void USART1_enter_DefaultMode_from_RESET(void);
extern void LEUART0_enter_DefaultMode_from_RESET(void);
extern void VCMP_enter_DefaultMode_from_RESET(void);
extern void WDOG_enter_DefaultMode_from_RESET(void);
extern void I2C0_enter_DefaultMode_from_RESET(void);
extern void TIMER0_enter_DefaultMode_from_RESET(void);
extern void TIMER1_enter_DefaultMode_from_RESET(void);
extern void PCNT0_enter_DefaultMode_from_RESET(void);
extern void PRS_enter_DefaultMode_from_RESET(void);
extern void PORTIO_enter_DefaultMode_from_RESET(void);
// [Config(Per-Module Mode)Transition Prototypes]$

// $[User-defined pin name abstraction]

#define HFXO_N_PIN          (14)
#define HFXO_N_PORT         (gpioPortB)

#define HFXO_P_PIN          (13)
#define HFXO_P_PORT         (gpioPortB)

#define I2C0_SCL_PIN        (7)
#define I2C0_SCL_PORT       (gpioPortD)

#define I2C0_SDA_PIN        (6)
#define I2C0_SDA_PORT       (gpioPortD)

#define TIMER2_CC0_PIN      (8)
#define TIMER2_CC0_PORT     (gpioPortA)

#define USART0_CLK_PIN      (12)
#define USART0_CLK_PORT     (gpioPortE)

#define USART0_CS_PIN       (13)
#define USART0_CS_PORT      (gpioPortE)

#define USART0_RX_PIN       (11)
#define USART0_RX_PORT      (gpioPortE)

#define USART0_TX_PIN       (10)
#define USART0_TX_PORT      (gpioPortE)

#define USART1_CLK_PIN      (7)
#define USART1_CLK_PORT     (gpioPortB)

#define USART1_CS_PIN       (8)
#define USART1_CS_PORT      (gpioPortB)

#define USART1_RX_PIN       (1)
#define USART1_RX_PORT      (gpioPortC)

#define USART1_TX_PIN       (0)
#define USART1_TX_PORT      (gpioPortC)

#define USB_DMPU_PIN        (0)
#define USB_DMPU_PORT       (gpioPortA)

#define USB_DM_PIN          (14)
#define USB_DM_PORT         (gpioPortC)

#define USB_DP_PIN          (15)
#define USB_DP_PORT         (gpioPortC)

// [User-defined pin name abstraction]$

#endif

